name: test_flutter_package
version: 1.0.0
description: >
  This package is a test
homepage: https://github.com/k-paxian/dart-package-publisher
environment:
  sdk: '>=2.6.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
